
spring.application.name=carrito
server.port=8086
server.address=0.0.0.0


spring.datasource.url=jdbc:mysql://db-carrito:3306/db_carrito?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=desarrollador
spring.datasource.password=password_seguro_123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.cloud.openfeign.client.config.default.connectTimeout=3000
spring.cloud.openfeign.client.config.default.readTimeout=5000

logging.level.cl.duoc.carrito=INFO
logging.level.org.hibernate.SQL=DEBUG

spring.cloud.compatibility-verifier.enabled=false