spring.application.name=resenas
server.port=8090
server.address=0.0.0.0

spring.datasource.url=jdbc:mysql://mysql_resenas:3306/db_resenas?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&autoReconnect=true
spring.datasource.username=desarrollador
spring.datasource.password=password_seguro_123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

catalogo.service.url=${CATALOGO_URL:http://entorno-catalogo:8082}
clientes.service.url=${CLIENTES_URL:http://entorno-clientes:8081}

spring.cloud.openfeign.client.config.default.connectTimeout=3000
spring.cloud.openfeign.client.config.default.readTimeout=5000

logging.level.cl.duoc.resenas=INFO
logging.level.org.hibernate.SQL=DEBUG