spring.application.name=catalogo
server.port=8082
server.address=0.0.0.0

spring.datasource.url=jdbc:mysql://db-catalogo:3306/db_catalogo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=desarrollador
spring.datasource.password=password_seguro_123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

inventario.service.url=${CLIENTES_URL:http://entorno-inventario:8083}
spring.cloud.compatibility-verifier.enabled=false